.PHONY: all say_hello generate clean

all: say_hello generate


say_hello:
	@echo "Hello World"


generate:
	@echo "Creating empty text files..."
	touch file-{01..10}.txt


clean:
	@echo "Cleaning up..."
	rm file-*.txt
